language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests -s --with-coverage
services:
  - redis-server
after_success:
  - coveralls
