language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
script:
  - PYTHONPATH=src:test py.test -v
services:
  - redis-server
after_success:
  - coveralls
